resolver: lts-12.16
extra-deps:
  - ../cabal2nix
  - hpack-0.31.1
  - infer-license-0.2.0
  - yaml-0.11.0.0
  - libyaml-0.1.0.0
  - git: https://github.com/fpco/stackage-curator.git
    commit: 73c5ed06602990c33d3fec1711e27875f283b6bf
  - git: https://github.com/jwiegley/gitlib.git
    commit: 70c99759b8b9377f67492fe29afb32f05882409d
    subdirs:
      - gitlib
      - gitlib-libgit2
nix:
  packages:
    - icu
    - openssl
    - zlib
